version: "1.1"

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --skipApiVersionCheck"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Integration"
      BlobStorage__ContainerName: "photos-dev"
      BlobStorage__ConnectionString: "${AZURITE_CONNECTION_STRING}"
      QueueStorageQueueName: "photo-invoice"
      StorageConnectionString: "${AZURITE_CONNECTION_STRING}" 
    depends_on:
      - azurite
